name: run main.py

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git
          pip install shareplum
          pip install pandas
          pip install datetime
          pip install requests
          pip install bs4
          pip install urllib3
          pip install ssl
      - name: execute py script # run main.py
        run: python main.py
