name: importssl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.7"
      - name: install python packages
        run: |
          python -m pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git
          pip install shareplum
          pip install requests
          pip install bs4
      - name: execute py script # run main.py
        run: python main.py
